### ISSUE TITLE
Unable to add default text box

### ISSUE THREAD

**Issue by Ayush4web** [porameht/nextjs-image-editor#2]
In the Text section when clicked on the 'Add Text Box' , throws an error and does not allow to add a text box with default styling 
![Screenshot 2024-11-05 at 8 53 04 PM](https://github.com/user-attachments/assets/ed8be34f-cc32-433a-9549-1476895e32f9)

**Comment by Ayush4web** [comment]
here is the PR for this issue -
https://github.com/porameht/nextjs-image-editor/pull/3

**Comment by porameht** [comment]
Thank you very much 😊
